### ISSUE TITLE
unable to use this project on my Javascript project

### ISSUE THREAD

**Issue by lironess** [falsecz/hbase-rpc-client#12]
Hi. Im writing a project that uses ES6 javascript (and H-Base 1.0).
This is a great project, but i can't use it because it is not compiled to Javascript.
I think all node.js modules should be compiled to Javascript, no matter in what language they were written, in order to use it properly and support projects that written only in Javascript.
I want you to add some script that makes the compilation while installing it by npm, and also change the package.json to reference the compiled index.js file.

**Comment by falsecz** [comment]
Hi, please try `npm install hbase-rpc-client@compiled`

**Comment by lironess** [comment]
Works perfectly !!!! Thank you !
and you did it so fast ! so you got a star from me ;)
BTW you can close the issue, just make sure that the compiled branch will be updated every time you add something new to the master :)

**Comment by falsecz** [comment]
Welcome. Now it's in master and npm 0.1.2

**Comment by RAKESH1256** [comment]
hi,
i am trying to connect to HBASE by generating js files using 'npm install hbase-rpc-client@compiled'
but i am unable to connect.
