### ISSUE TITLE
unable to connect to hbase server using nodejs(hbase-rpc-client)

### ISSUE THREAD

**Issue by RAKESH1256** [falsecz/hbase-rpc-client#14]
hi,
i am trying to connect to HBASE by generating js files using 'npm install hbase-rpc-client@compiled'
but i am unable to connect.

**Comment by falsecz** [comment]
send me sample code and hbase version

**Comment by RAKESH1256** [comment]
hbase version is 1.o and below is the code.
----------
var hbase = require('hbase-rpc-client');
var client = hbase({
    zookeeperHosts: 'localhost:2181',
    zookeeperRoot: '/hbase',
    rootRegionZKPath: '/root-region-server',
    rpcTimeout: 30000,
    pingTimeout: 30000,
    callTimeout: 5000
});
--------
var del;
del = new hbase.Delete(rowkey);
client.delete(tablename ,del, function(err, res) {
    return console.log(arguments);
});
---------------

**Comment by falsecz** [comment]
`zookeeperHosts` should be an aray

try to add error handler 
```
client.on('error', function(err) {
  console.log(err)
})
```

and run it in debug mode
`DEBUG=* node ....`

**Comment by RAKESH1256** [comment]
no error and 'client.on' i snot avilable.

**Comment by falsecz** [comment]
and debug output?

**Comment by RAKESH1256** [comment]
it didn't returned any error.

**Comment by falsecz** [comment]
try this 
```js
var hbase = require('hbase-rpc-client')
var client = hbase({
    zookeeperHosts: ['localhost:2181'],
    zookeeperRoot: '/hbase',
    rootRegionZKPath: '/root-region-server',
    rpcTimeout: 30000,
    pingTimeout: 30000,
    callTimeout: 5000
});

client.on('error', function(err) {
  console.log(err)
})

var del;
del = new hbase.Delete("asdsd");
client.delete("tablename" ,del, function(err, res) {
    return console.log(arguments);
});
```

and

`DEBUG=* node index.js`
should dump something like this
```
  hbase-client delete on table: tablename delete: {"row":"asdsd","familyMap":{}} +0ms
  hbase-region locateRegion table: tablename row: asdsd +3ms
   ...
```
send me full output

**Comment by RAKESH1256** [comment]
tried this got error.
--
{ [NO_NODE: Exception: NO_NODE[-101]]
  code: -101,
  name: 'NO_NODE',
  path: undefined,
  message: 'Exception: NO_NODE[-101]' }

**Comment by falsecz** [comment]
where did you found `rootRegionZKPath: '/root-region-server',` 
`rootRegionZKPath` should be `/meta-region-server` (this is default value, you can omit it)

**Comment by RAKESH1256** [comment]
ok, guy who seated up our our hbase environment said that rootRegionZKPath: '/root-region-server'
and i tryed changing it to ' rootRegionZKPath: '/meta-region-server'' got error.
----------
{ exceptionClassName: 'java.io.IOException',
  stackTrace: 'java.io.IOException\n\tat org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2069)\n\tat org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:107)\n\tat org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:130)\n\tat org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:107)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: java.lang.NullPointerException\n\tat org.apache.hadoop.hbase.quotas.RegionServerQuotaManager.checkQuota(RegionServerQuotaManager.java:182)\n\tat org.apache.hadoop.hbase.quotas.RegionServerQuotaManager.checkQuota(RegionServerQuotaManager.java:136)\n\tat org.apache.hadoop.hbase.regionserver.RSRpcServices.scan(RSRpcServices.java:2131)\n\tat org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:31443)\n\tat org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2035)\n\t... 4 more\n',
  hostname: null,
  port: null,
  doNotRetry: false }
{ '0': 
   { exceptionClassName: 'java.io.IOException',
     stackTrace: 'java.io.IOException\n\tat org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2069)\n\tat org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:107)\n\tat org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:130)\n\tat org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:107)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: java.lang.NullPointerException\n\tat org.apache.hadoop.hbase.quotas.RegionServerQuotaManager.checkQuota(RegionServerQuotaManager.java:182)\n\tat org.apache.hadoop.hbase.quotas.RegionServerQuotaManager.checkQuota(RegionServerQuotaManager.java:137)\n\tat org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:1775)\n\tat org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:31439)\n\tat org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2035)\n\t... 4 more\n',
     hostname: null,
     port: null,
     doNotRetry: false } }
-----

**Comment by falsecz** [comment]
see hbase master and regionserver logs

**Comment by wision** [comment]
`/root-region-server` is used in hbase 0.94 which is not supported in this client.. 0.96 and above uses `/meta-region-server`

**Comment by RAKESH1256** [comment]
ok let me check

**Comment by discit** [comment]
Hi falsecz,

I ran into same problem, I tried 
DEBUG=* node index.js
It dump this

  hbase-client delete on table: tablename delete: {"row":"asdsd","familyMap":{}} +0ms
  hbase-region locateRegion table: tablename row: asdsd +3ms

Could you help what to do next?

**Comment by wision** [comment]
@discit can you please post whole debug log?

**Comment by discit** [comment]
Thanks discit for you response!

that is the whole debug logs (what it show in the console when I run the above sample). However, I realized that there was a different from above sample that I used  var hbase = require('hbase-client') instead var hbase = require('hbase-rpc-client').

I changed the code to var hbase = require('hbase-rpc-client') - so it has the same sample code above. I ran the DEBUG=* node test.js (test.js is the file that I created using the script above) then get the following logs:

var client = HBase.create({
                   ^
TypeError: Object function (options) {
    var Client;
    Client = require('./client');
    return new Client(options);
  } has no method 'create'
    at Object.<anonymous> (/home/tlg/node_modules/hbase-rpc-client/test5.js:3:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by wision** [comment]
@discit please remove the port from zookeeperHosts.. also, are you sure about that zookeeperRoot value?

**Comment by discit** [comment]
@wision Thanks alot, i changed port to 2181 and zookeeperRoot: '/hbase' then it worked!

I am newbie to nodejs and hbase, I now want to build a nodejs class that can provide CRUD for hbase (version 1.0.1.1). However, I've not found any document or sample about nodejs to access hbase (using hbase-rpc-client). Could you help me on this?

**Comment by wision** [comment]
@discit isn't our readme good enough? https://github.com/falsecz/hbase-rpc-client/blob/master/README.md
If the problem is that our examples are in coffeescript (not javascript), then just translate it to javacsript at http://coffeescript.org/

**Comment by discit** [comment]
Thanks wision!
I tried to write code to get a row of data as follow:

var hbase = require('hbase-rpc-client');
var client = hbase({
    zookeeperHosts: ['localhost'],
    zookeeperRoot: '/hbase',
    rootRegionZKPath: '/meta-region-server',
    rpcTimeout: 30000,
    pingTimeout: 30000,
    callTimeout: 5000
});

client.on('error', function(err) {
  console.log(err)
})

var get;
get = new hbase.Get("jsmith");
console.log('start ...');
//console.log(arguments);
client.get("customer" ,get, function(err, res) {
    console.log(res);
    return console.log(arguments);
});
console.log('end.');



It returns the following (the data is in hexa format <Buffer 6a 73 6d 69 74 68>)

Could you advice me how can I parse the data into string?
Also, how can I handle if error occur?


{ row: <Buffer 6a 73 6d 69 74 68>,
  cols:
   { 'addr:city': { value: <Buffer 68 63 6d>, timestamp: [Object] },
     'addr:state': { value: <Buffer 43 4f>, timestamp: [Object] },
     'order:date':
      { value: <Buffer 31 30 2d 31 38 2d 32 30 31 34>,
        timestamp: [Object] },
     'order:numb': { value: <Buffer 36 36 36 36>, timestamp: [Object] } },
  columns:
   [ { family: <Buffer 61 64 64 72>,
       qualifier: <Buffer 63 69 74 79>,
       value: <Buffer 68 63 6d>,
       timestamp: [Object] },
     { family: <Buffer 61 64 64 72>,
       qualifier: <Buffer 73 74 61 74 65>,
       value: <Buffer 43 4f>,
       timestamp: [Object] },
     { family: <Buffer 6f 72 64 65 72>,
       qualifier: <Buffer 64 61 74 65>,
       value: <Buffer 31 30 2d 31 38 2d 32 30 31 34>,
       timestamp: [Object] },
     { family: <Buffer 6f 72 64 65 72>,
       qualifier: <Buffer 6e 75 6d 62>,
       value: <Buffer 36 36 36 36>,
       timestamp: [Object] } ] }

**Comment by falsecz** [comment]
try `toString()`  or `toBuffer().toString()` on value

**Comment by discit** [comment]
Thanks falsecz!
but toString() or toBuffer().toString() does not work.

I don't know how to parse the value and decode it to string.

for example I want to extract to get 'addr:city' and its value "68 63 6d" (but "68 63 6d" need to be decoded to "hcm").

Could you help me on this?

**Comment by michioaida** [comment]
This works for me:
```javascript
var cityVal = new Buffer(resultsObj.cols["addr:city"].value).toString();
console.log(cityVal);
```

**Comment by discit** [comment]
great thanks michioaida, it works!
