### ISSUE TITLE
Wrapping simple operations

### ISSUE THREAD

**Issue by moshewe** [falsecz/hbase-rpc-client#20]
Lets consider an Increment.
I'm seeing a lot of boilerplate code when people just increment a cell - they have to create an Increment object, call its put method, etc.

Can't we just wrap it for them?

**Comment by wision** [comment]
Main idea was to keep as similar interface as native java client (hence the Increment object). But I agree that it could work as mput for example, which takes array of simple objects (as well as array of Put objects) and creates Put objects internally. Pull requests are welcome:)

**Comment by moshewe** [comment]
Ok, I'm working on it right now, so I'll fork when I have enough
functionality tested and available.

**Comment by moshewe** [comment]
Can I write the extensions in Javascript?

**Comment by falsecz** [comment]
coffee-script should be better
