### ISSUE TITLE
Zookeeper watcher not initialized with timeout parameters

### ISSUE THREAD

**Issue by moshewe** [falsecz/hbase-rpc-client#21]
I had a weird bug where the zookeeper was unresponsive and yet no error was thrown by the client. I added more zookeepers and all went back to normal. 

I see that the zookeeper watcher isn't initialized with any timeout setting - can that be problematic?

**Comment by wision** [comment]
Is this reproducible? zookeeper-watcher uses 20s timeout by default

**Comment by moshewe** [comment]
Try giving an invalid zookeeper address.
It simply didn't t/o for me.

Even if it's 20s, should be customizable.

**Comment by wision** [comment]
Ok.. I had a look into the code. That zookeeper timeout I mentioned is applied after zk connection is closed (meaning zookeeper-watcher received expired or disconnected event). I will make that configurable via hbase-rpc-client. (https://github.com/node-modules/zookeeper-watcher/blob/master/lib/zookeeper-watcher.js#L65)

This module has its own timeout for zookeeper initial connection and that is specified by rpcTimeout in the options and that is actually the one you asked for. I will try to explain what particular timeouts mean in the readme.

In the end, I still don't see any real issue (besides not being able to set zookeeper-watcher reconnect timeout). Invalid zookeeper address results in an error. If I try to kill zookeeper and start it again, the client does reconnect to the zk.

My question stays the same.. is your issue reproducible?

**Comment by moshewe** [comment]
Haven't managed to since we updated the application, maybe it was indeed
the expiry timeout that caused this weird behavior.

**Comment by wision** [comment]
Parameter zookeeperReconnectTimeout added in #27.
