### ISSUE TITLE
ERROR: EMFILE, too many open files

### ISSUE THREAD

**Issue by gblue1223** [falsecz/hbase-rpc-client#22]
hbase returns 'ERROR: EMFILE, too many open files' error message when I open many pages on my website.

It seems 'hbase-rpc-client' doesn't close connection with habse. I've checked by 'netstate' but  'ESTABLISHED' connections were never closed.

How can I close connection explicityly?

**Comment by falsecz** [comment]
Could you please provide example? There is no need to close connections, there is just one connection per region server.

**Comment by gblue1223** [comment]
I have had experience in Thrift with PHP. And in Thrift I have to disconnect the connection after execute a command like put, delete, scan. So I thought disconnection is rightful.

However, if the connection remains during its running time, are there extra data transfer between a hbase server and a web server? like heart-beat packet?

And what happens if the connection lost with some reason like network problem?

**Comment by wision** [comment]
Currently there's no extra data transfer, no ping onto connected region servers (might be implemented though). If the connection is lost, the client removes the server from connections (it doesn't try to reconnect).

**Comment by gblue1223** [comment]
Thanks for quick response. Do you have a plan to implement a function to reconnect? Or where should I look at to reconnect the server?

**Comment by wision** [comment]
It does reconnect when it's needed.. what I meant is that it doesn't reconnect right away.

**Comment by gblue1223** [comment]
So, you mean, it will reconnect when it gets the commands(put, delete, scan). Am I right?

**Comment by wision** [comment]
Yes.

**Comment by gblue1223** [comment]
Okay, many thanks.

**Comment by wision** [comment]
You're welcome.
