### ISSUE TITLE
RegionConnection connection pool

### ISSUE THREAD

**Issue by moshewe** [falsecz/hbase-rpc-client#25]
From as much as I can see in the source code, there's a single connection to each region server. Making a connection pool mechanism for each region server will accelerate concurrent queries.

**Comment by falsecz** [comment]
You can use some generic pool with multiple hbase client instances.
This is java like implementation.

**Comment by moshewe** [comment]
Why not just supply it as part of the library?

**Comment by wision** [comment]
This is just not how you want the hbase client to behave. There's limited number of connections available for all the clients on every region server and creating pool connections would just result in quick depletion of that limit. I also don't see how it would considerably accelerate concurrent queries as you mentioned.

As falsecz said:
> You can use some generic pool with multiple hbase client instances.
> This is java like implementation.
