### ISSUE TITLE
RPC Client remote connection

### ISSUE THREAD

**Issue by tk-codes** [falsecz/hbase-rpc-client#34]
Hello there

```
  #localhost works
  var client = hbase({
    zookeeperHosts: ['localhost:2181'],
    zookeeperRoot: '/hbase',
    rootRegionZKPath: '/meta-region-server',
    rpcTimeout: 30000,
    pingTimeout: 30000,
    callTimeout: 5000
  });

#remotely, it doesn't work
  var client = hbase({
    zookeeperHosts: ['192.168.15.166:2181'],
    zookeeperRoot: '/hbase',  #is this path correct?
    rootRegionZKPath: '/meta-region-server',
    rpcTimeout: 30000,
    pingTimeout: 30000,
    callTimeout: 5000
  });
```

Error message when connecting remotely..
```
Failed to connect to zookeeper. zkHosts: [192.168.15.166:2181] zkRoot: '/hbase'
```

I am a windows user running a vagrant machnine with hbase. If I would run my node.js app on my vagrant machine, your rpc-client connections works.
But when I run the same app on my windows remotely, I get the above mentioned error message. 

But on my server I can see that my client-ip is listed correctly..
![hbase](https://cloud.githubusercontent.com/assets/3751899/12913330/4f5da308-cf1e-11e5-8708-331814de7e5d.JPG)

Do you have any idea, what could be the problem?

**Comment by wision** [comment]
Hi, your zookeeperRoot is correct. Please post DEBUG=* with simple script. Are you sure that your vagrant ip (192.168.15.166) is reachable from your windows machine?

**Comment by tk-codes** [comment]
Here is the result of debug..
![hbase](https://cloud.githubusercontent.com/assets/3751899/12916355/0b493a4c-cf32-11e5-8899-6ad32c959c44.JPG)

I guess so, because if i type a false vagrant-ip, then my ip (192.168.15.1) is removed from the clients list of zookeeper. But I am not quite sure.

**Comment by wision** [comment]
Your habase reports that the region server is running on localhost.. that's the reason why it won't connect from your windows machine. Do you run your hbase in pseudo-distributed mode? That might be the problem.

**Comment by tk-codes** [comment]
Yes, that's right. By the way, I use this vagrant settings (https://github.com/zsiciarz/vagrant-hbase)
So isn't it possible to connect from windows?

**Comment by wision** [comment]
No idea with the pseudo-distributed mode.. but you can start zookeeper in your vagrant and then run hbase in fully distributed mode. That should work.

**Comment by tk-codes** [comment]
Ok. I give it a try. Thank you very much for your help.
