### ISSUE TITLE
addColumn - different column families

### ISSUE THREAD

**Issue by tk-codes** [falsecz/hbase-rpc-client#35]
```
    // Get row key
    var get = new hbase.Get(rowid);
    get.addColumn("b", transactionId);
    get.addColumn("d",transactionId);
```
I have two different column families, namley "b" and "d".
If I add the both families to select a specified column qualifier (transactionId), it doesn't return both columns. Rather it returns only the last column family (d).

Is there any way to fix this problem?

**Comment by wision** [comment]
Thanks for reporting.. fix will be published soon.

**Comment by tk-codes** [comment]
great! it works. Thank you for fixing the issue.
