### ISSUE TITLE
Is there any plan for Kerberos secured HBase server ?

### ISSUE THREAD

**Issue by lsarrazin** [falsecz/hbase-rpc-client#45]

**Comment by wision** [comment]
Not anytime soon.. but pull requests are welcome!

**Comment by ccbeloy** [comment]
Hi,
Can someone provide some sort of guidance for the implementation of Kerberos Auth?
Not sure where to start here...Client.proto? ConnectionHeader?
If I could get a kerberos token, can I pass in rpc call header?

Thanks in advance!

**Comment by wision** [comment]
Hello. Unfortunately I can only point you to hbase code https://github.com/apache/hbase, as I don't know  the answer myself.
