### ISSUE TITLE
PageFilter not working?

### ISSUE THREAD

**Issue by YiannisGkoufas** [falsecz/hbase-rpc-client#46]
Hi there,

was wondering whether PageFilter is supported.
I tried this:

`scanner.setFilter({
        pageFilter: {
            pageSize: 1
        }
    });`

but it doesn't seem to take into consideration.
Also maybe there is some other way I can do scans with limit?

Thanks!

**Comment by wision** [comment]
Hello,

currently the scan is unlimited. Scan itself gets first 100 rows and returns them one by one (if you use .each() method).. if you ask for 101th result, the client will query hbase again for another 100 rows.

That might also be the reason why pageFilter does not work.

**Comment by YiannisGkoufas** [comment]
Ah I see, so as a workaround for the limit I should just keep a counter and call .next() ?
What is the difference with .each() method?

**Comment by wision** [comment]
.next() just returns one result (and it's up to you to call it again).

.each() requires first parameter to be a function and it iterates through all results of the scan via calling .next() internally and applies given function to its result.

**Comment by wision** [comment]
Yesterday I misread PageFilter documentation (https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/filter/PageFilter.html). hbase-rpc-client does work as supposed. Using `pageFilter: { pageSize: 1 }` should result in getting first row from each region. I did test the client with various values and it did work.

**Comment by YiannisGkoufas** [comment]
So for me, I have a table with 10 regions and I specify pageFilter: { pageSize:1} but still get more than thousands results ( I just stop it myself )

**Comment by YiannisGkoufas** [comment]
Sorry for the stupid question....but I cannot find an example for javascript to iterate the results of a scanner....Is it possible to post a snippet? Just to validate the pageFilter

**Comment by wision** [comment]
Those thousands of results sound like a bug.. I'll look into it later. As for iterating, here is some quick code I came up with (sorry it's done with CS -> JS tool and I didn't have time to test it):
```JavaScript
var iterate, scan;

scan = client.getScanner('my-test-table');

scan.setFilter({
  pageFilter: {
    pageSize: 1
  }
});

iterate = true;

async.whilst(function() {
  return iterate;
}, function(next) {
  scan.next(function(err, row) {
    if (!row) {
      iterate = false;
      return next();
    }
    console.log(row);
    next();
  });
}, function(err) {
  console.log('all results iterated');
});```

**Comment by YiannisGkoufas** [comment]
great! it's working I think (in the sense that it returns one result)
but I think it doesn't stop the recursion and getting:

function formatPrimitive(ctx, value) {
                        ^

RangeError: Maximum call stack size exceeded
    at formatPrimitive (util.js:452:25)
    at formatValue (util.js:261:19)
    at inspect (util.js:143:10)
    at exports.format (util.js:24:24)
    at Console.log (console.js:39:34)
    at /home/johngouf/test-rpc/app.js:40:13
    at /home/johngouf/test-rpc/node_modules/hbase-rpc-client/lib/scan.js:229:20
    at Scan.module.exports.Scan.Scan._getData (/home/johngouf/test-rpc/node_modules/hbase-rpc-client/lib/scan.js:93:16)
    at Scan._getData (/home/johngouf/test-rpc/node_modules/hbase-rpc-client/lib/scan.js:4:59)
    at Scan.module.exports.Scan.Scan.next (/home/johngouf/test-rpc/node_modules/hbase-rpc-client/lib/scan.js:223:19)

**Comment by YiannisGkoufas** [comment]
Here is the solution from @stefano81

```
async.whilst(function() {
  return iterate;
}, function(next) {
  scan.next(function(err, row) {
    if (!Object.keys(row).length) {
      iterate = false;
      return next();
    }
    count++; 
    next();
  });
}, function(err) {
  console.log(count);
  console.log('all results iterated');
});
```

Cheers!

**Comment by wision** [comment]
@YiannisGkoufas What's the result of your test? Is this still an issue?

**Comment by AmolSGawali** [comment]
YiannisGkoufas, 

Have you tried filterList?
Below is java code in which I have used pageFilter.

Filter filter = new PrefixFilter(Bytes.toBytes(rowKey));
			Filter pageFilter = new PageFilter(100);

FilterList filterList = new FilterList();
		    filterList.addFilter(filter);
		    filterList.addFilter(pageFilter);

scan.setFilter(filterList);
ResultScanner resultScanner = table.getScanner(scan);
