### ISSUE TITLE
Binary filter doesn't seem to work

### ISSUE THREAD

**Issue by ccbeloy** [falsecz/hbase-rpc-client#48]
Please let me know what is wrong with this filter?

var createBinaryFilter = function(cf, cq, value){
    return {singleColumnValueFilter:{
        columnFamily: cf,
        columnQualifier: cq,
        compareOp: "EQUAL",
        comparator:{
            binaryComparator:{comparable: { value : new Buffer(value)}}
        },
        filterIfMissing: false,
        latestVersionOnly: true
    }};
}

**Comment by wision** [comment]
Hi. I see nothing wrong with the filter. Tried it and it worked. Can you please post whole code?

**Comment by ccbeloy** [comment]
Hi, this already works for me my connection was incorrect. Thanks.
