### ISSUE TITLE
how to prevent other people from access to my hbase server?

### ISSUE THREAD

**Issue by cosdy** [falsecz/hbase-rpc-client#49]
`'use strict';

var zookeeper = require('node-zookeeper-client');

var crypto = require('crypto');

let key = crypto.createHash('sha1').update('username:password').digest().toString('base64');

var id = new zookeeper.Id('digest', 'username:' + key);
var acl = new zookeeper.ACL(zookeeper.Permission.ALL, id);

var client = zookeeper.createClient('192.168.28.129:2181');

client.once('connected', function () {
  console.log('Connected to the server.');

  client.setACL(
      '/hbase', [acl], function (error, acls, stat) {
        if (error) {
                console.log(error.stack);
               return;
        }
        console.log('New ACL is set.');
      }
    );
});

client.connect();`

i want to use it to set the username and password for hbase server.

**Comment by cosdy** [comment]
but i can access the zookeeper use `var hbase = require("hbase-rpc-client");

		client = hbase({
		  zookeeperHosts: ["192.168.28.129:2181"],
		  zookeeperRoot: "/hbase"
		});`

**Comment by cosdy** [comment]
how to prevent other people from access to my hbase server？use kerberos？how to do it？

**Comment by wision** [comment]
Currently there is no authentication method implemented in this hbase client.

**Comment by cosdy** [comment]
Dose this hbase client can  implement the kerberos authentication method in theroy? just only java api?nodejs can not?

**Comment by wision** [comment]
It is possible in nodejs, but if you want more details, I can only repeat what I said at #45. You'll have to look into java code for inspiration (https://github.com/apache/hbase).
