### ISSUE TITLE
does scan api  only can get one row each time？

### ISSUE THREAD

**Issue by cosdy** [falsecz/hbase-rpc-client#50]
i found scan api has each method，does it mean scan api   only can get one row each time？but the java
api can get all the rows at the same time. does  this scan api is not the really scan ,just imitate the really scan?

**Comment by wision** [comment]
Our scanner uses rpc Scan, so it is really a scan. This implementation gets 100 rows by default in each scan call, meaning that if you have a scan which matches 1234 results (for simplicity, let's assume only one region server) and you call each method on such scan, it will do 13 hbase calls to retrieve all the results.
