### ISSUE TITLE
just scan the first 100 results within the hbase server

### ISSUE THREAD

**Issue by cosdy** [falsecz/hbase-rpc-client#51]
hi,
	 i have two questions:

	1) my mobile app has about 200 thousand users now, i have used mysql for my database, but
	i want to use hbase to replace it for all,  is it a good database for mobile app which has mass users(so it will has very hign Qps)

	2) for example, i have a scan which matches 1234 results, but i just want to get the first 100 results, i hope the scanner just scan the first 100 results within the hbase server, and stop on the 101, not the all 1234 results, so it will obviously reduce the server burden, how to do this?

																																		cosdy from China

**Comment by wision** [comment]
Hi,
1) I'm not able to tell because I don't know the use case for your application. Mysql is able to handle hundreds of millions rows though.
2) Like I said in your previous issue, yes, it will fetch only 100 rows by default.
