### ISSUE TITLE
Using RegexStringComparator 

### ISSUE THREAD

**Issue by rajkaran** [falsecz/hbase-rpc-client#56]
What should be patternFlags and charset value? I want it to ignore case. UTF-8 charset will work?

```
message RegexStringComparator {
  required string pattern = 1;
  required int32 pattern_flags = 2;
  required string charset = 3;
}
```

**Comment by wision** [comment]
You need to consult hbase documentation for that: https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/filter/RegexStringComparator.html

**Comment by rajkaran** [comment]
For those looking for the same answer:

Below are the possible options for pattern flags- 
```
CANON_EQ - 128
CASE_INSENSITIVE - 2
COMMENTS - 4
DOTALL - 32
LITERAL - 16
MULTILINE - 8
UNICODE_CASE - 64
UNICODE_CHARACTER_CLASS - 256
UNIX_LINES - 1
```

below are the possible options for charsets
```
US-ASCII
ISO-8859-1
UTF-8
UTF-16BE
UTF-16LE
UTF-16
```

Seems like, in Java regex is case sensitive by default.
