### ISSUE TITLE
hbase client error: { NO_NODE: Exception: NO_NODE[-101]

### ISSUE THREAD

**Issue by mahiruddinseikh** [falsecz/hbase-rpc-client#59]
```
var hbase = require ("hbase-rpc-client");

client = hbase({
    zookeeperHosts: ["localhost"],
    zookeeperRoot: "/zookeeper",
    zookeeperReconnectTimeout: 20000,
    rootRegionZKPath: "/meta-region-server",
    rpcTimeout: 30000,
    callTimeout: 5000,
    tcpNoDelay: 'no',
    tcpKeepAlive: 'yes',
    realUser: "hbase",
    effectiveUser: "someEffectiveUser"
});
client.on("connect", (data) =>{
    console.log ("hbase client error:", data)
});

client.on("error", (err) =>{
console.log ("hbase client error:", err)
});
```

I am using this code for connect my hbase server with node.js, but getting the below exceptions.
```
hbase client error: { NO_NODE: Exception: NO_NODE[-101]
    at ConnectionManager.onSocketData (D:\Projects\Test\hbase.connection.test\node_modules\hbase-rpc-client\node_modules\node-zookeeper-client\lib\ConnectionManager.js:570:35)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
  code: -101,
  name: 'NO_NODE',
  path: undefined,
  message: 'Exception: NO_NODE[-101]' }
```

System Information --
Hbase : 1.1.7
Hadoop : 2.7.0
Node : 6.11.2

**Comment by wision** [comment]
Your `zookeeperRoot` value is most likely incorrect. Try `/hbase` instead.

**Comment by mahiruddinseikh** [comment]
Updated zookeeperRoot: "/hbase", but getting another error..
`var hbase = require ("hbase-rpc-client");

client = hbase({
    zookeeperHosts: ["localhost"],
    zookeeperRoot: "/hbase",
    zookeeperReconnectTimeout: 20000,
    rootRegionZKPath: "/meta-region-server",
    rpcTimeout: 30000,
    callTimeout: 5000,
    tcpNoDelay: 'no',
    tcpKeepAlive: 'yes',
    realUser: "hbase",
    effectiveUser: "someEffectiveUser"
});
client.on("connect", (data) =>{
    console.log ("hbase client error:", data)
});

client.on("error", (err) =>{
console.log ("hbase client error:", err)
});`

**Comment by wision** [comment]
Is the zookeeper hostname correct? Is it located on localhost as the script you're running?

**Comment by SumantaBee** [comment]
@wision the zookeeper instance is running on a different ip port. We used localhost here for security purpose

**Comment by wision** [comment]
Well.. you need to make sure that you use correct zookeeper connection string and that it is accessible from the server you are running the script. But it seems weird, that before you connected to zk and got NO_NODE error and now you are not able to connect at all.

**Comment by SumantaBee** [comment]
@wision Yeah it is accessible because, we are trying to run haredb console from the same machine (localhost itself) and it is being able to fetch the schema, create schema, columns etc. But getting error while running any transaction. 
We also tried running the same node app from the serverside. There also we are getting the same issue. Does it have something to do with hbase version?

**Comment by wision** [comment]
Nope.. zookeeper connection has nothing to do with the hbase version. The client first connects to zookeeper and then gets hbase configuration and connects to hbase.

**Comment by SumantaBee** [comment]
Thanks. And is there any well documented site that has a tutorial for hbase hello world setup?

**Comment by wision** [comment]
Sorry, I have no idea.. I'd try to find it on google.

**Comment by SumantaBee** [comment]
Oh ok. np. Thanks for the help anyway
________________________________
