### ISSUE TITLE
Getting 'put' and 'delete' errors with 0.1.13

### ISSUE THREAD

**Issue by shekenahglory** [falsecz/hbase-rpc-client#64]
not sure why this has changed, but the callback from `client.put` and `client.delete` now has the arguments `put/delete [tablename]` instead of `null { result: null, processed: true }`

It looks like the interpreter is taking the arguments from the `_action` method rather than the callback function: https://github.com/falsecz/hbase-rpc-client/blob/master/src/client.coffee#L325

**Comment by wision** [comment]
Could you please try 0.1.14?

**Comment by shekenahglory** [comment]
looks good now, thanks
