### ISSUE TITLE
Is there good way to collect the rows from multiple queries?

### ISSUE THREAD

**Issue by leimao** [falsecz/hbase-rpc-client#67]
I wanted to do multiple queries from HBase, collect the returning rows, and display all of them on one HTML page. I could probably do it using a nested way. However, I don't know if the client has any support for such functionalities. 
PS: I found the client is not compatible with the npm package async.

**Comment by wision** [comment]
You can use `mget` to get multiple results.
I've had no problems using this package with async.

**Comment by leimao** [comment]
This sounds great. Let me try.

**Comment by leimao** [comment]
It seems that ``mget`` supports queries from one table using multiple keys. If I want to do queries using multiple keys from multiple tables, I should using async package. Is my understanding correct?

**Comment by leimao** [comment]
This is my code of collecting multiple query results to dictionary using ``async`` package. However, the other code below this patch of code will be executed before the client gets and puts the query result into the dictionary.
```
    var async = require("async");
    var client = hbase({
        /* Zookeeper information for cluster */
        zookeeperHosts: ['10.0.0.2:2181'],
        zookeeperRoot: '/hbase-unsecure'
    });
    var obj = {"pickup": [community_pickup_key, hbaseTableCrimeByWeather], "dropoff": [community_dropoff_key, hbaseTableCrimeByWeather], "go": [routeGo_key, hbaseTableTaxiTrips], "back": [routeBack_key, hbaseTableTaxiTrips]};
    var configs = {};

    async.forEachOf(obj, (value, key, callback) => {
        let [queryKey, hBaseTable] = value;
        client.get(hBaseTable, queryKey, function(err, row){
            configs[key] = row;
        });callback();}, 
        err => {
            if (err) {console.error(err.message);}
        }
    );
```

**Comment by wision** [comment]
You cannot query multiple tables with one command.
Your code does not work, because you're calling async callback right after `get()`. You should be calling it in the callback inside the `get()`.

It should look like this:
```    var async = require("async");
    var client = hbase({
        /* Zookeeper information for cluster */
        zookeeperHosts: ['10.0.0.2:2181'],
        zookeeperRoot: '/hbase-unsecure'
    });
    var obj = {"pickup": [community_pickup_key, hbaseTableCrimeByWeather], "dropoff": [community_dropoff_key, hbaseTableCrimeByWeather], "go": [routeGo_key, hbaseTableTaxiTrips], "back": [routeBack_key, hbaseTableTaxiTrips]};
    var configs = {};

    async.forEachOf(obj, (value, key, callback) => {
        let [queryKey, hBaseTable] = value;
        client.get(hBaseTable, queryKey, function(err, row){
            configs[key] = row;
            callback();
        })}, 
        err => {
            if (err) {console.error(err.message);}
        }
    );```

**Comment by leimao** [comment]
Thank you very much. Your suggestion helped a lot.
